from enum import StrEnum
class DocumentType(StrEnum):
    RENT_AGREEMENT="RENT_AGREEMENT"; EMPLOYMENT_OFFER="EMPLOYMENT_OFFER"; WEBSITE_TERMS="WEBSITE_TERMS"; FREELANCE_CONTRACT="FREELANCE_CONTRACT"; UNKNOWN="UNKNOWN"
